# Generated by Django 2.2.3 on 2019-07-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190722_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='item',
            field=models.TextField(),
        ),
    ]
