# Generated by Django 2.2.3 on 2019-07-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20190723_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
